version: '3.8'
services:
  service-1:
    container_name: service-1
    build: ./service-1
    image: service-1:latest
    ports:
    - target: 5000
      published: 5000
    depends_on:
    - "service-4"
  service-2:
    container_name: service-2
    build: ./service-2
    image: service-2:latest
    ports:
    - target: 5001
      published: 5001
  service-3:
    container_name: service-3
    build: ./service-3
    image: service-3:latest
    ports:
    - target: 5002
      published: 5002
  service-4:
    container_name: service-4
    build: ./service-4
    image: service-4:latest
    ports:
    - target: 5003
      published: 5003
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - "service-1"