version: '3.8'
services:
  service-1:
    build: ./service-1
    image: waledcapw/service-1
    deploy:
      replicas: 2
    ports:
    - target: 5000
      published: 5000
    depends_on:
    - "service-4"
  service-2:
    build: ./service-2
    image: waledcapw/service-2
    deploy:
      replicas: 2
    ports:
    - target: 5001
      published: 5001
  service-3:
    build: ./service-3
    image: waledcapw/service-3
    deploy:
      replicas: 2
    ports:
    - target: 5002
      published: 5002
  service-4:
    build: ./service-4
    image: waledcapw/service-4
    deploy:
      replicas: 2
    ports:
    - target: 5003
      published: 5003